[build]
  command = "npm ci && npm run build"
  publish = ".next"
  
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Используем Next.js Runtime вместо плагина для лучшей SSR поддержки
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
