name = "neuroexpert"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

[env.production]
name = "neuroexpert-production"

[env.production.vars]
NODE_VERSION = "18"